### ISSUE TITLE
sudo.exe: cannot execute command: dir

### ISSUE THREAD

**Issue by liboshi** [mattn/sudo#2]
Hi Mattn,

I am very intrested with this tool, then I pull it to my local WIndows 10x64 machine. But I got error which I mentioned in title.

Steps:
`go version`
go version go1.8.3 windows/amd64
`go get github.com/mattn/sudo`
`sudo.exe dir`
sudo.exe: cannot execute command: dir

Any proconditions should I do before use this tool?
Thanks in advance.

**Comment by mattn** [comment]
Ah, sorry. I have dir.exe provided from msys. I'll update README.md
You should do with `sudo cmd /c dir`.
