### ISSUE TITLE
Go really needed? 

### ISSUE THREAD

**Issue by lroellin** [mattn/sudo#4]
Do users really need Go installed? From what I've tinkered around with Go (and please correct me cause I could be very wrong) you can compile a binary. 

Wouldn't it be easier to just release that binary? 

For me right now, it seems like I need the SDK as a user, when I could go on with just a compiled binary :)

**Comment by thde** [comment]
@lroellin You could build the binary using [AppVeyor](https://www.appveyor.com/) and push it to Github releases.

**Comment by mattn** [comment]
I'll add release script using AppVeyor in next chance to do.

**Comment by mattn** [comment]
done https://github.com/mattn/sudo/releases

**Comment by Mause** [comment]
You should probably enable the link to the releases tab?

**Comment by mattn** [comment]
Do you mean adding link into README.md ?

**Comment by Mause** [comment]
I guess - there used to a be link you could enable at the top, but I can't find the option anymore

**Comment by lroellin** [comment]
The link is still there, it's not a top-level tab but you can see it when browsing a repo :)
